version: '3.5'

services:
  nuxt:
    build:
      context: .
    image: aspiryx-app
    container_name: aspiryx-app
    environment:
      - NITRO_SSL_CERT="${SSL_CERT}"
      - NITRO_SSL_KEY="${SSL_KEY}"
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
