version: '3.5'

services:
  nuxt:
    build:
      context: .
    image: aspiryx-app
    container_name: aspiryx-app
    volumes:
      - /etc/letsencrypt/archive/aspiryx.space/:/usr/src/app/certs/
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
