name: Deployment

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if cd ${{ github.event.repository.name }}; then git pull; else git clone ${{ github.event.repository.ssh_url }}; fi
            cd ${{ github.event.repository.name }}
            echo "${{ secrets.ENV_FILE }}" > .env
            docker stop aspiryx-app || true && docker rm aspiryx-app || true
            SSL_CERT="${{ secrets.SSL_CERT }}" SSL_KEY="${{ secrets.SSL_KEY }}" docker compose up --build -d